[package]
name = "alpha_vantage_rust"
version = "0.1.0"
edition = "2021"
authors = ["Dwight Browne <dwight@dwightjbrowne.com>"]
description = "Rust Alphavantage API to Postgres"
license = "MIT"
repository = "https://github.com/dwightbrowne/alpha_vantage_rust"
readme = "README.md"
keywords = ["Alphavantage", "postgres"]
categories = ["database", "finance"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lints.rust]
unused_imports = "deny"

[dependencies]
bigdecimal = "0.4.3"
bincode = "1.3.3"
chrono = { version = "0.4.19", features = ["serde"] }
chrono-tz = "0.8.3"
crc = "3.2.1"
crc32fast = "1.4.0"
csv = "1.2.1"
diesel = { version = "2.0.4", features = ["postgres", "chrono", "uuid"] }
dotenvy = "0.15.7"
indicatif = "0.17.8"
lazy_static = "1.4.0"
reqwest = { version = "0.11.6", features = ["blocking","json"] }
ring = { version = "0.17.3", features = [] }
serde = { version = "1.0.159", features = ["derive"] }
serde_derive = "1.0.159"
serde_json = "1.0.84"
serde_with = { version = "3.3.0", features = [] }
thiserror = { version = "2.0.3" }
uuid = { version = "1.3.3", features = ["serde", "v4"] }

[package.metadata.git-cliff.changelog]
header = "All notable changes to this project will be documented in this file."
body = "..."
footer = "<!-- generated by git-cliff -->"
# see [changelog] section for more keys

[package.metadata.git-cliff.git]
conventional_commits = true
commit_parsers = []
filter_commits = false
# see [git] section for more keys:w:"::w"
