services:
  postgres:
    build:
      context: .
      dockerfile: dev_alpha_docker_file
    image: "dev_alpha_docker_file"
    container_name: ${D_PG_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${D_POSTGRES_DB}
      POSTGRES_USER: ${D_POSTGRES_USER}
      POSTGRES_PASSWORD: ${D_POSTGRES_PASSWORD}
      PGDATA: ${D_PGDATA}
    volumes:
      - d_alpha:/data/d_alpha
    ports:
      - "6999:5432"
    restart: unless-stopped
volumes:
  d_alpha:
    external: true