services:
  postgres:
    build:
      context: .
      dockerfile: test_alpha_docker_file
    image: "test_alpha_docker_file:latest"
    container_name: ${T_PG_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${T_POSTGRES_DB}
      POSTGRES_USER: ${T_POSTGRES_USER}
      POSTGRES_PASSWORD: ${T_POSTGRES_PASSWORD}
      PGDATA: ${T_PGDATA}
      DATABASE_URL: ${T_DATABASE_URL}
    volumes:
      - test_alpha:/data/test_alpha
    ports:
      - "8999:5432"
    restart: unless-stopped
volumes:
  test_alpha:
    external: true