-- Your SQL goes here
ALTER TABLE overviews
    ALTER COLUMN MarketCapitalization TYPE BIGINT,
    ALTER COLUMN EBITDA TYPE BIGINT,
    ALTER COLUMN BookValue TYPE DOUBLE PRECISION;

-- Update the overviewexts table
ALTER TABLE overviewexts
    ALTER COLUMN RevenueTTM TYPE BIGINT,
    ALTER COLUMN GrossProfitTTM TYPE BIGINT,
    ALTER COLUMN Beta TYPE DOUBLE PRECISION,
    ALTER COLUMN annWeekHigh TYPE DOUBLE PRECISION,
    ALTER COLUMN annWeekLow TYPE DOUBLE PRECISION,
    ALTER COLUMN fiftyDayMovingAverage TYPE DOUBLE PRECISION,
    ALTER COLUMN twohDayMovingAverage TYPE DOUBLE PRECISION,
    ALTER COLUMN SharesOutstanding TYPE DOUBLE PRECISION;