drop table if exists topicmaps cascade;
drop table if exists tickersentiments cascade ;
drop table if exists authormaps cascade ;
drop table if exists feeds cascade ;
drop table if exists newsoverviews cascade ;
drop table if exists overviews cascade  ;
drop table if exists overviewexts cascade ;
drop table if exists symbols cascade ;
drop table if exists topstats cascade ;
drop table if exists summaryprices cascade ;
drop table if exists intradayprices cascade ;